# ─── Rutas de la aplicación ──────────────────────────────────
app_dir: /opt/dandydash-api
frontend_dir: /opt/dandydash-frontend
log_dir: /var/log/dandydash
ssl_dir: /etc/ssl/dandydash

# ─── Usuario del sistema ─────────────────────────────────────
app_user: dandydash-app

# ─── PostgreSQL ──────────────────────────────────────────────
db_name: dandydashdb
db_user: dandydash
db_pass: "DBPass_DandyDash2026!"

# ─── Dominio y red ───────────────────────────────────────────
domain: dandydash.local
app_ip: 192.168.20.10

# ─── Samba4 AD ───────────────────────────────────────────────
ldap_server: "192.168.30.10"
ldap_server2: "192.168.30.11"
ldap_base: "DC=dandydash,DC=local"
ldap_bind_user: "CN=Administrator,CN=Users,DC=dandydash,DC=local"
ldap_bind_pass: "DandyAdmin2026!"

# ─── Seguridad de la app ─────────────────────────────────────
admin_password: "Admin_DandyDash2026!"
jwt_secret: "fdecf9d92afb0f7b7ce383ac22d30e4526fa6ae034ae2d6d664616a5ac6c674c"
secret_key: "6bbab643c51281b34aef9949386497556b9dcc6216bca9585b5f1299a8ca34e4"

# ─── MFA ─────────────────────────────────────────────────────
mfa_issuer: "DandyDash"
