- name: Recarregar Nginx
  service:
    name: nginx
    state: reloaded

- name: Reiniciar Nginx
  service:
    name: nginx
    state: restarted

- name: Reiniciar DandyDash API
  service:
    name: dandydash-api
    state: restarted

- name: Reiniciar PostgreSQL
  service:
    name: postgresql
    state: restarted
