[dandydash_app]
192.168.20.10 ansible_user=admin-kk

[samba]
samba1 ansible_host=192.168.30.10
samba2 ansible_host=192.168.30.11

[monitor]
dandydash-monitor ansible_host=192.168.40.10

[servidors:children]
dandydash_app
samba
monitor

[servidors:vars]
ansible_user=admin
ansible_become=yes
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
